#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 28 04:55:14 2018

@author: fiction
p45


Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""
import math

#tri =  [n*(n+1)/2 for n in range(1,10000000)]
#pen = [n*(3*n-1)/2 for n in range(1,10000000)]
#hexa = [n*(2*n-1) for n in range(1,10000000)]

for i in range(1170,10000000):
    he = i*(2*i-1)
    if  ((-1+math.sqrt(1+8*he))/2)**2==int(((-1+math.sqrt(1+8*he))/2)**2):
        if ((1+math.sqrt(1+24*he))/6)**2 ==int(((1+math.sqrt(1+24*he))/6)**2):
            print(he)
            break