#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 22 01:03:34 2018

@author: fiction
ploblem12


The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""
import time
start =time.time()
tri = 1
for i in range(2,1000000):
    tri = tri + i
    divisors = 2
    print(tri)
    for k in range(2,int(tri**0.5)+1):
        if tri%k == 0:
            if k == tri**0.5:
                divisors+=1
            else:    
                divisors +=2
    if divisors > 500:
        break
    print("divisors="+str(divisors))
    
elapsed = (time.time() - start)
print(tri)
print(elapsed)
